---
# tasks/install-debian.yml - Install AmneziaWG on Debian/Ubuntu via PPA

- name: Assert debian version
  ansible.builtin.assert:
    that:
      - ansible_distribution_major_version == 13
      - ansible_distribution == 'Debian'
    msg: "Debian 13 is not supported"